INSERT INTO bookmarks (title, url, description, rating)
VALUES 
('bookmark 1', 'https://bookmark1.com', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia purus sed eros rhoncus, eget ultricies nunc bibendum. Nunc fringilla laoreet tortor, non vestibulum felis. Nunc tincidunt eros eu porta hendrerit. Sed ac commodo magna. Mauris consectetur nulla vel lectus condimentum ultricies. Nullam id mi ut tortor elementum elementum. Donec placerat nulla sit amet diam iaculis, vitae auctor arcu tempor. Fusce aliquam quis nunc id dignissim. Donec porta faucibus purus id euismod.', '3'),

('bookmark 2', 'https://bookmark2.com', 'Ut congue nibh quam, vel pharetra ipsum tempor dictum. Proin varius sit amet orci aliquam blandit. Fusce ut tellus et turpis facilisis imperdiet quis sed arcu. Quisque vitae tempor libero. Sed eleifend, nisi ut interdum scelerisque, odio felis tempor tortor, a scelerisque nulla turpis ac dui. Quisque condimentum sapien eros, sed dignissim risus rhoncus nec. In viverra tellus erat, quis porta arcu feugiat id.', '4'),

('bookmark 3', 'https://bookmark3.com', 'Aenean sit amet lorem nec purus aliquam iaculis. Morbi et dolor et elit suscipit hendrerit suscipit et orci. Donec vitae eros laoreet tortor vestibulum maximus quis ut sem. Proin eget magna non ligula cursus suscipit. Nulla volutpat ligula quis nulla consectetur ornare. In sollicitudin efficitur neque quis sagittis. Maecenas sed sapien lobortis, pharetra sapien quis, rhoncus leo. Proin quis tempus urna. Donec commodo, nisl sed laoreet viverra, nisl ipsum sodales nunc, sit amet varius nulla turpis mattis metus. Quisque vitae euismod ligula, a porttitor elit. In eget cursus turpis. Sed et diam lobortis, tempor quam ultricies, commodo massa.', '5'),

('bookmark 4', 'https://bookmark4.com', 'Nunc malesuada odio sem, nec convallis turpis viverra eget. In hac habitasse platea dictumst. Cras consectetur tincidunt ex eget pulvinar. Donec vel dolor quis tellus suscipit ultricies. Aliquam dictum volutpat lectus quis fermentum. Praesent vitae velit eget ante rhoncus lacinia. In erat felis, condimentum sed venenatis vel, suscipit quis nunc. Integer nisi nunc, pharetra vel sapien a, consequat sagittis nisi. Vivamus sodales porta orci. Pellentesque vel ligula felis. Ut tempus nulla accumsan quam varius facilisis.', '3'),

('bookmark 5', 'https://bookmark5.com', 'Praesent semper lacus non ante mollis dapibus. Quisque mattis, odio ac vehicula feugiat, massa nunc lobortis lectus, non sagittis enim leo eget arcu. Pellentesque convallis erat sed ligula aliquam feugiat. Nulla hendrerit quam condimentum, placerat lacus venenatis, varius lorem. Nulla facilisi. Morbi tristique rutrum felis vel condimentum.', '1'),

('bookmark 6', 'https://bookmark6.com', 'Sed interdum porttitor augue eget feugiat. Sed a viverra sapien. Quisque semper libero vitae efficitur efficitur. Quisque sed orci commodo, auctor lorem ac, dapibus quam. Praesent sagittis vitae purus vitae pharetra. Praesent vitae est ornare, condimentum justo vitae, vulputate felis. Duis facilisis, turpis non fermentum aliquet, nisi sem aliquam massa, non semper mi ligula eu ante.', '4');